# -*- coding: utf-8 -*-
"""
Cloud daily report index service.

GitHub Actions stores complete daily Markdown reports under ``cloud_reports``.
This service exposes those reports as read-only history records so the local web
UI can show reports generated by scheduled cloud runs.
"""
from __future__ import annotations

import json
import logging
import os
import re
import subprocess
import urllib.error
import urllib.parse
import urllib.request
from datetime import date, datetime, time, timezone, timedelta
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

logger = logging.getLogger(__name__)

CLOUD_REPORT_STOCK_CODE = "DAILY"
CLOUD_REPORT_QUERY_PREFIX = "cloud-report-"
DEFAULT_CLOUD_REPORT_REPOSITORY = "goneveitvet240-svg/daily_stock_analysis"


class CloudReportService:
    """Read-only access to GitHub Actions daily aggregate reports."""

    def __init__(
        self,
        repo_root: Optional[Path] = None,
        repository: Optional[str] = None,
        branch: Optional[str] = None,
        remote_enabled: Optional[bool] = None,
        timeout_seconds: Optional[float] = None,
    ) -> None:
        self.repo_root = Path(repo_root) if repo_root else Path(__file__).resolve().parents[2]
        self.cloud_dir = self.repo_root / "cloud_reports"
        self.index_path = self.cloud_dir / "index.json"
        self.repository = (
            repository
            or os.getenv("CLOUD_REPORTS_REPOSITORY")
            or self._detect_repository()
            or DEFAULT_CLOUD_REPORT_REPOSITORY
        )
        self.branch = branch or os.getenv("CLOUD_REPORTS_BRANCH") or "main"
        self.timeout_seconds = float(
            timeout_seconds
            if timeout_seconds is not None
            else os.getenv("CLOUD_REPORTS_FETCH_TIMEOUT_SECONDS", "4")
        )
        if remote_enabled is None:
            remote_flag = os.getenv("CLOUD_REPORTS_REMOTE_ENABLED", "true").strip().lower()
            self.remote_enabled = remote_flag not in {"0", "false", "no", "off"}
        else:
            self.remote_enabled = remote_enabled

    def list_history_items(
        self,
        stock_code: Optional[str] = None,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
    ) -> List[Dict[str, Any]]:
        """Return cloud daily reports in the same shape as history list items."""
        if stock_code and stock_code.strip().upper() != CLOUD_REPORT_STOCK_CODE:
            return []

        items: List[Dict[str, Any]] = []
        for entry in self._load_entries():
            report_date = self._entry_date(entry)
            if start_date and report_date and report_date < start_date:
                continue
            if end_date and report_date and report_date > end_date:
                continue
            items.append(self._entry_to_history_item(entry))

        items.sort(key=lambda item: self._sort_datetime(item.get("created_at")), reverse=True)
        return items

    def get_detail(self, record_id: str) -> Optional[Dict[str, Any]]:
        """Return a pseudo history detail record for a cloud report."""
        entry = self._find_entry(record_id)
        if not entry:
            return None

        compact = entry["date_compact"]
        file_path = entry.get("file") or f"cloud_reports/report_{compact}.md"
        run_url = entry.get("run_url") or ""
        title = entry.get("title") or f"{self._display_date(compact)} 每日股票分析日报"
        created_at = entry.get("created_at") or self._default_created_at(compact)

        return {
            "id": -int(compact),
            "query_id": f"{CLOUD_REPORT_QUERY_PREFIX}{compact}",
            "stock_code": CLOUD_REPORT_STOCK_CODE,
            "stock_name": title,
            "report_type": "full",
            "report_language": "zh",
            "created_at": created_at,
            "model_used": None,
            "analysis_summary": "这是一份由 GitHub Actions 自动生成的每日汇总报告。点击“完整报告”查看 Telegram 同款 Markdown 内容。",
            "operation_advice": "查看完整报告",
            "trend_prediction": "日报已生成",
            "sentiment_score": 50,
            "sentiment_label": "中性",
            "ideal_buy": None,
            "secondary_buy": None,
            "stop_loss": None,
            "take_profit": None,
            "news_content": None,
            "raw_result": {
                "cloud_report": True,
                "report_language": "zh",
                "file": file_path,
                "run_url": run_url,
            },
            "context_snapshot": {
                "source": entry.get("source") or "github_actions",
                "run_id": entry.get("run_id"),
                "run_number": entry.get("run_number"),
            },
        }

    def get_news(self, record_id: str, limit: int = 20) -> List[Dict[str, str]]:
        """Cloud aggregate reports do not have per-record news rows."""
        if self.is_cloud_record_id(record_id):
            return []
        return []

    def get_markdown_report(self, record_id: str) -> Optional[str]:
        """Return Markdown content for a cloud report."""
        entry = self._find_entry(record_id)
        if not entry:
            return None

        compact = entry["date_compact"]
        file_path = entry.get("file") or f"cloud_reports/report_{compact}.md"
        local_path = self.repo_root / file_path
        if local_path.exists():
            try:
                return local_path.read_text(encoding="utf-8")
            except OSError as exc:
                logger.warning("读取本地云端日报失败 %s: %s", local_path, exc)

        if not self.remote_enabled:
            return None

        return self._fetch_text(self._raw_url(file_path))

    def is_cloud_record_id(self, record_id: str) -> bool:
        """Return whether a record id refers to a cloud report."""
        return self._date_compact_from_record_id(record_id) is not None

    def _load_entries(self) -> List[Dict[str, Any]]:
        merged: Dict[str, Dict[str, Any]] = {}

        if self.remote_enabled:
            for entry in self._read_remote_entries():
                merged[entry["date_compact"]] = entry

        for entry in self._read_local_entries():
            merged[entry["date_compact"]] = entry

        return list(merged.values())

    def _find_entry(self, record_id: str) -> Optional[Dict[str, Any]]:
        compact = self._date_compact_from_record_id(record_id)
        if not compact:
            return None

        for entry in self._load_entries():
            if entry.get("date_compact") == compact:
                return entry
        return None

    def _read_local_entries(self) -> List[Dict[str, Any]]:
        if not self.index_path.exists():
            return []
        try:
            payload = json.loads(self.index_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            logger.warning("读取本地云端日报索引失败: %s", exc)
            return []
        return list(self._normalize_entries(payload, source="local"))

    def _read_remote_entries(self) -> List[Dict[str, Any]]:
        payload = self._fetch_json(self._raw_url("cloud_reports/index.json"))
        if not payload:
            return []
        return list(self._normalize_entries(payload, source="remote"))

    def _normalize_entries(self, payload: Any, source: str) -> Iterable[Dict[str, Any]]:
        reports = payload.get("reports") if isinstance(payload, dict) else payload
        if not isinstance(reports, list):
            return []

        normalized: List[Dict[str, Any]] = []
        for raw in reports:
            if not isinstance(raw, dict):
                continue
            compact = self._date_compact_from_entry(raw)
            if not compact:
                continue
            file_path = raw.get("file") or raw.get("path") or f"cloud_reports/report_{compact}.md"
            date_text = raw.get("date") or self._display_date(compact)
            normalized.append({
                "date": date_text,
                "date_compact": compact,
                "title": raw.get("title") or f"{date_text} 每日股票分析日报",
                "file": str(file_path),
                "created_at": raw.get("created_at") or self._default_created_at(compact),
                "run_id": raw.get("run_id"),
                "run_number": raw.get("run_number"),
                "run_url": raw.get("run_url"),
                "source": raw.get("source") or source,
            })
        return normalized

    def _entry_to_history_item(self, entry: Dict[str, Any]) -> Dict[str, Any]:
        compact = entry["date_compact"]
        return {
            "id": -int(compact),
            "query_id": f"{CLOUD_REPORT_QUERY_PREFIX}{compact}",
            "stock_code": CLOUD_REPORT_STOCK_CODE,
            "stock_name": entry.get("title") or f"{self._display_date(compact)} 每日股票分析日报",
            "report_type": "full",
            "sentiment_score": None,
            "operation_advice": "日报",
            "created_at": entry.get("created_at") or self._default_created_at(compact),
        }

    def _fetch_json(self, url: str) -> Optional[Any]:
        text = self._fetch_text(url)
        if not text:
            return None
        try:
            return json.loads(text)
        except json.JSONDecodeError as exc:
            logger.warning("云端日报索引不是合法 JSON: %s", exc)
            return None

    def _fetch_text(self, url: str) -> Optional[str]:
        headers = {
            "Accept": "application/vnd.github.raw",
            "User-Agent": "daily-stock-analysis",
        }
        token = os.getenv("CLOUD_REPORTS_TOKEN") or os.getenv("GITHUB_TOKEN")
        if token:
            headers["Authorization"] = f"Bearer {token}"

        request = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(request, timeout=self.timeout_seconds) as response:
                return response.read().decode("utf-8")
        except (urllib.error.URLError, TimeoutError, OSError) as exc:
            logger.debug("获取云端日报失败 %s: %s", url, exc)
            return None

    def _raw_url(self, path: str) -> str:
        quoted_branch = urllib.parse.quote(self.branch, safe="")
        quoted_path = urllib.parse.quote(path.lstrip("/"), safe="/")
        return f"https://raw.githubusercontent.com/{self.repository}/{quoted_branch}/{quoted_path}"

    def _date_compact_from_record_id(self, record_id: str) -> Optional[str]:
        text = str(record_id).strip()
        if text.startswith(CLOUD_REPORT_QUERY_PREFIX):
            compact = text[len(CLOUD_REPORT_QUERY_PREFIX):]
            return compact if self._valid_compact_date(compact) else None

        try:
            int_id = int(text)
        except (TypeError, ValueError):
            return None

        if int_id >= 0:
            return None
        compact = str(abs(int_id))
        return compact if self._valid_compact_date(compact) else None

    def _date_compact_from_entry(self, raw: Dict[str, Any]) -> Optional[str]:
        compact = str(raw.get("date_compact") or "").strip()
        if self._valid_compact_date(compact):
            return compact

        date_value = str(raw.get("date") or "").strip()
        compact = date_value.replace("-", "")
        if self._valid_compact_date(compact):
            return compact

        file_path = str(raw.get("file") or raw.get("path") or "")
        match = re.search(r"report_(\d{8})\.md$", file_path)
        if match and self._valid_compact_date(match.group(1)):
            return match.group(1)
        return None

    @staticmethod
    def _valid_compact_date(value: str) -> bool:
        if not re.fullmatch(r"\d{8}", value or ""):
            return False
        try:
            datetime.strptime(value, "%Y%m%d")
        except ValueError:
            return False
        return True

    @staticmethod
    def _display_date(compact: str) -> str:
        return f"{compact[:4]}-{compact[4:6]}-{compact[6:8]}"

    def _entry_date(self, entry: Dict[str, Any]) -> Optional[date]:
        compact = entry.get("date_compact")
        if not compact:
            return None
        try:
            return datetime.strptime(compact, "%Y%m%d").date()
        except ValueError:
            return None

    def _default_created_at(self, compact: str) -> str:
        report_date = datetime.strptime(compact, "%Y%m%d").date()
        default_time = datetime.combine(report_date, time(18, 30), tzinfo=timezone(timedelta(hours=8)))
        return default_time.isoformat()

    def _sort_datetime(self, value: Optional[str]) -> datetime:
        if value:
            try:
                parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
                if parsed.tzinfo is None:
                    parsed = parsed.replace(tzinfo=timezone(timedelta(hours=8)))
                return parsed
            except ValueError:
                pass
        return datetime.min.replace(tzinfo=timezone.utc)

    def _detect_repository(self) -> Optional[str]:
        try:
            result = subprocess.run(
                ["git", "config", "--get", "remote.origin.url"],
                cwd=self.repo_root,
                check=False,
                capture_output=True,
                text=True,
                timeout=2,
            )
        except (OSError, subprocess.TimeoutExpired):
            return None
        if result.returncode != 0:
            return None
        return self._parse_github_repository(result.stdout.strip())

    @staticmethod
    def _parse_github_repository(remote_url: str) -> Optional[str]:
        patterns = [
            r"github\.com[:/](?P<repo>[^/\s]+/[^/\s]+?)(?:\.git)?$",
            r"^git@github\.com:(?P<repo>[^/\s]+/[^/\s]+?)(?:\.git)?$",
        ]
        for pattern in patterns:
            match = re.search(pattern, remote_url)
            if match:
                return match.group("repo")
        return None
